### ISSUE TITLE
关于博客的一个小建议

### ISSUE THREAD

**Issue by wwhai** [JasonkayZK/JasonkayZK.github.io#41]
![image](https://user-images.githubusercontent.com/20577297/135251551-cab0f484-d12c-4e07-8bb9-247f41c615bc.png)
出现白色的时候，文字看不清楚了，这里加个深色遮罩层估计好点

**Comment by JasonkayZK** [comment]
之前考虑过，但是因为是文章封面是随机的，不好判断，就没搞了；
